<?php

namespace PlatformBundle\Repository;

/**
 * SubProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
